addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.9.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-ghpages" % "0.6.3")
addSbtPlugin("com.47deg"  % "sbt-microsites" % "1.3.4")
addSbtPlugin("org.scalameta"  % "sbt-mdoc" % "2.2.23")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.10")
addSbtPlugin("com.eed3si9n" % "sbt-unidoc" % "0.4.3")