addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-ghpages" % "0.6.3")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.5.1")
addSbtPlugin("com.47deg"  % "sbt-microsites" % "1.2.1")
addSbtPlugin("org.scalameta"  % "sbt-mdoc" % "2.2.7")
addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.5.3")
